model_type: fast_unet # tasnet/fast_unet/unet/unet2/e3net
dataset:
  process:
    batch_size: 8
    num_workers: 1
  segment:
    segment: 10
    enroll_segment: 20
    sample_rate: 16000
    random_select: 0.1
  train:
    csv_path: 'audio/csv/mix_train.csv'
    enroll_csv_path: 'audio/csv/jnas_enroll.csv'
    noise_csv_path: 'audio/csv/noise_train.csv' # on-the-fly mixing
  valid:  
    csv_path: 'audio/csv/mix_valid.csv'
    enroll_csv_path: 'audio/csv/jnas_enroll.csv'
    noise_csv_path: 'audio/csv/noise_valid.csv'
  test:
    csv_path: 
    enroll_path: 
    noise_path:
augment:
  # on-the-fly mixing
  mixing:
    min_snr: 0
    max_snr: 20
  opus:
    sample_rate: 16000
    frame_duration: 20
    min_bps: 6000
    max_bps: 20000
    min_packet_loss_rate: 0.0
    max_packet_loss_rate: 0.3
    decode_missing_packet_rate: 0.5
    use: true
  reverb:
    params:
      sample_rate: 16000
      min_rt60: 0.2
      max_rt60: 1.0
      snr: 60
      room_size:
        - 4.8
        - 5.8
        - 2.5
      mic_loc:
        - 0.5
        - 2.9
        - 1.0
    source_loc:
      - 0.3
      - 2.9
      - 1.2
    source_loc_range:
      - 0.1
      - 0.1
      - 0.1
    noise_loc:
      - 3.0
      - 2.9
      - 1.2
    noise_loc_range:
      - 1.7
      - 2.0
      - 0.5
    use: true
trainer:
  accelerator: 'auto'
  accumulate_grad_batches: 5
  max_epochs: 400
  precision: '16-mixed'
  profiler: 'simple'
  gradient_clip_val: 5.
optimizer:
  lr: 1.e-4
logger:
  save_dir: './fast_unet'
  version: 1
  name: 'lightning_logs'
checkpoint:
  monitor: 'valid_loss'
  filename: 'checkpoint_{epoch}-{step}-{valid_loss:.3f}'
  save_last: True
  save_top_k: 1
  mode: 'min'
  every_n_epochs: 1
loss:
  ce_loss:
    weight: 0.1
  l1_loss:
    weight: 0.0
  stft_loss:
    use: True
    weight: 1.0
  pesq_loss:
    use: False
    weight: 1.0
  sdr_loss:
    use: False
    weight: 1.0
  stoi_loss:
    use: False
    weight: 1.0
speaker:
  adpt_type: none
# models
tasnet:
  kernel_size: 20
  in_channels: 256
  enc_channels: 256
  conv_channels: 256
  num_blocks: 6
  block_kernel_size: 3
  num_repeats: 4
  num_speakers: 307
  resample: 1
unet: #unet/unet2
  attention: True
  normalize: False #True
  floor: 0.001
  resample: 1
  depth: 5
  in_channels: 512  #1
  mid_channels: 512 #512 #48
  out_channels: 512 #1
  max_channels: 10000
  kernel_size: 3 #8
  growth: 1 #2
  rescale: 0.1
  stride: 2 #4
  reference: 0.1
  causal: True
  num_speakers: 307
ctc:
  use: False
  weight: 1.0
  parameters:
  kernel_size: 8
  stride: 4
  padding: 4
  chout: 256
  outdim: 41
e3net:
  depth: 4
  encoder:
    chin: 1
    chout: 2048
    kernel_size: 400
    stride: 160
    padding: 200
  decoder:
    chin: 2048
    chout: 1
    kernel_size: 400
    stride: 160
    padding: 0
    output_padding: 0
  lstm:
    dim: 1024
    hidden_dim: 256
  speaker:
    chin: 2048
    chout: 256
    kernel_size: 3
    num_speakers: 307
  concat:
    x_dim: 2048
    s_dim: 256
    output_dim: 256
  masking:
    x_dim: 256
    output_dim: 2048
emformer:
  input_dim: 256
  num_heads: 8
  ffn_dim: 1024
  num_layers: 5
  segment_length: 20
  dropout: 0.1
  activation: 'relu'
  left_context_length: 0
  right_context_length: 5 
  max_memory_size: 0
  tanh_on_mem: False
sepformer:
  channels: 256
  kernel_size: 16
  stride: 8
  