model_type: tasnet # tasnet/unet/unet2
dataset:
  process:
    batch_size: 8
    num_workers: 2
  segment:
    segment: none
    enroll_segment: none
    sample_rate: 16000
  train:
    csv_path: 'audio/csv/train_3p.csv'
    enroll_csv_path: 'audio/csv/enroll_3p.csv'
    noise_csv_path: 'audio/csv/noise_train.csv' # on-the-fly mixing
  valid:  
    csv_path: 'audio/csv/valid_3p.csv'
    enroll_cav_path: 'audio/csv/enroll_3p.csv'
    noise_csv_path: 'audio/csv/noise_valid.csv'
  test:
    csv_path: 
    enroll_path: 
    noise_path:
augment:
  # on-the-fly mixing
  mixing:
    min_snr: 0
    max_snr: 20
  opus:
    sample_rate: 16000
    frame_duration: 20
    min_bps: 1000
    max_bps: 6000
    min_packet_loss_rate: 0.0
    max_packet_loss_rate: 0.3
    decode_missing_packet_rate: 0.5
    use: true
  reverb:
    sample_rate: 16000
    room_size:
      - 4.8
      - 5.8
      - 2.5
    mic_loc:
      - 0.5
      - 2.9
      - 1.0
    source_loc:
      - 0.3
      - 2.9
      - 1.2
    source_loc_range:
      - 0.1
      - 0.1
      - 0.1
    noise_loc:
      - 3.0
      - 2.9
      - 1.2
    noise_loc_range:
      - 1.7
      - 2.0
      - 0.5
    min_rt60: 0.2
    max_rt60: 1.0
    snr: 60
    use: true
trainer:
  accelerator: 'auto'
  accumulate_grad_batches: 5
  max_epochs: 400
  precision: '16-mixed'
  profiler: 'simple'
  gradient_clip_val: 5.
optimizer:
  lr: 1.e-4
logger:
  save_dir: './'
  version: 2
  name: 'lightning_logs'
checkpoint:
  monitor: 'valid_loss'
  filename: 'checkpoint_{epoch}-{step}-{valid_loss:.3f}'
  save_top_k: 1
  mode: 'min'
  every_n_epochs: 1
loss:
  ce_loss:
    weight: 0.1
  stft_loss:
    use: True
    weight: 1.0
  pesq_loss:
    use: False
    weight: 1.0
  sdr_loss:
    use: False
    weight: 1.0
  stoi_loss:
    use: False
    weight: 1.0
speaker:
  adpt_type: none
# models
tasnet:
  kernel_size: 20
  in_channels: 256
  enc_channels: 256
  conv_channels: 512
  num_blocks: 6
  block_kernel_size: 3
  num_repeats: 4
  num_speakers: 307
  resample: 1
unet: #unet/unet2
  attention: True
  normalize: False #True
  floor: 0.001
  resample: 2
  depth: 5
  in_channels: 1
  mid_channels: 256 #512 #48
  out_channels: 1
  max_channels: 10000
  kernel_size: 8
  growth: 1 #2
  rescale: 0.1
  stride: 4
  reference: 0.1
  causal: True
  num_speakers: 307
