eos: '</s>'
bos: '<s>'
dataset:
  process:
    batch_size: 16
    num_workers: 1
  segment:
    segment: 20
    sample_rate: 16000
  train:
    csv_path: 'data/braille_train.csv'
  valid:  
    csv_path: 'data/braille_valid.csv'
  test:
    csv_path: 'data/braille_valid.csv' #'/export/20230515/test_braille.csv'
  tokenizer: 'data/braille_pretrained/vocab.json'
  max_length: 1000
analysis:
  sample_rate: 16000
  nfft: 400
  win_length: 400
  hop_length: 160
  n_mels: 80
  global_mean_std: 'data/global_mean_std.npz'
  sort_by_len: true
augment:
  specaug: false
  time_mask: 80
  freq_mask: 80
transducer:
  blank: 0
  vocab_size: 71
  hidden_size: 144 #512
  num_layers: 8 #16 #17
  num_heads: 4 #8
  cell_size: 320 #640
logger:
  save_dir: './logs/version_1'
model_output: 'best.pt'
decode_output: 'decode.trn'
max_epochs: 100
optimizer:
  lr: 1.e-4
 