model_type: conformer
eos: </s>
# dataset
dataset:
  process:
    batch_size: 8
    num_workers: 2
  segment:
    segment: 10
    sample_rate: 16000
  train:
    csv_path: '/export/20230515/train_braille.csv'
  valid:  
    csv_path: '/export/20230515/valid_braille.csv'
  test:
    csv_path: '/export/20230515/test_braille.csv'
  tokenizer: '/export/20230515/braille_tokenizer/vocab.json'
  max_length: 1000
analysis:
  sample_rate: 16000
  nfft: 400
  win_length: 400
  hop_length: 160
  n_mels: 80
  global_mean_std: '/export/20230515/global_mean_std.npz'
augment:
  specaug: false
  time_mask: 80
  freq_mask: 80
# trainer parameters
trainer:
  accelerator: 'auto'
  accumulate_grad_batches: 5
  max_epochs: 400
  precision: '16-mixed'
  profiler: 'simple'
  gradient_clip_val: 5.
optimizer:
  lr: 1.e-4
logger:
  save_dir: './'
  version: 1
  name: 'lightning_logs'
checkpoint:
  monitor: 'valid_loss'
  filename: 'checkpoint_{epoch}-{step}-{valid_loss:.3f}'
  save_top_k: 3
  mode: 'min'
  every_n_epochs: 1
model:
  dim_input: 80
  dim_model: 256 # conformer(L)
  dim_output: 71
  num_heads: 8
  dim_feedforward: 256
  num_encoder_layers: 16
  num_decoder_layers: 8
  kernel_size: 31
  cntf_channels: 104
  cntf_kernel_size: 7
  
